[package]
name = "geodatafusion-parquet"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Parquet Geometry/Geography TableProvider for DataFusion"
categories = { workspace = true }
rust-version = { workspace = true }


[dependencies]
arrow-schema = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
datafusion-datasource = { workspace = true }
datafusion-datasource-parquet = { workspace = true }
geo = { workspace = true }
object_store = { workspace = true }
parquet = { version = "57.2.0", features = ["parquet-geospatial", "object_store"]}
wkt = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
criterion = { version = "0.5.1", features = ["async_tokio"] }
datafusion = { workspace = true, features = ["parquet", "sql"] }
geo = { workspace = true }
geo-traits = { workspace = true }
geoarrow-array = { workspace = true, features = ["test-data"] }
geodatafusion = { workspace = true }
object_store = { workspace = true, features = ["http"] }
tokio = { workspace = true, features = ["macros", "fs", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "intersects"
harness = false
